### PR TITLE
my poor pull request ;-; (sadaka XD)

### PR DESCRIPTION
**Pull request by Doha-Helmaoui**

### CODE REVIEW

**Comment by oussamabonnor1** [comment]
You should add code too, jst the screenshots are not a good enough contribution

**Comment by Doha-Helmaoui** [comment]
i had a hard time with LFS TvT but next time i'll contribute with a full project !

**Comment by oussamabonnor1** [comment]
You shouldnt upload stuff like project settings and unity dependencies, try to include a unity .gitignore to ignore those files during upload. only code and art assets should be uploaded. Also do not upload any .exe files, instead: include them in the release tab of the repo.

**Comment by Doha-Helmaoui** [comment]
wakarimashita commander 👮‍♀️

**Pull request merged**
